### ISSUE TITLE
Error while running host.pyw

### ISSUE THREAD

**Issue by Suman99pro** [codedak/chatbot#4]
/usr/bin/python2.7 /home/suman/chatbot/host.pyw
 Traceback (most recent call last): File "/home/suman/chatbot/host.pyw", line 7, in <module>
 sess, model, enc_vocab, rev_dec_vocab = execute.init_session(sess, conf='seq2seq_serve.ini') 
File "/home/suman/chatbot/execute.py", line 242, in init_session 
gConfig = get_config(conf)
 File "/home/suman/chatbot/execute.py", line 38, in get_config 
confints = [ (key, int(value)) for key,value in parser.items('ints') ] 
File "/usr/lib/python2.7/ConfigParser.py", line 642, in items
 raise NoSectionError(section)
 ConfigParser.NoSectionError: No section: 'ints'

**Comment by shahabaejaz** [comment]
i also got the same error ..any solutions ?

**Comment by Chaitanya009** [comment]
@Suman99pro try sess, model, enc_vocab, rev_dec_vocab = execute.init_session(sess, conf='seq2seq.ini')

**Comment by zegoudemehdi** [comment]
also the same error ! any solution please??
