### ISSUE TITLE
TypeError: sampled_loss() got an unexpected keyword argument 'logits'

### ISSUE THREAD

**Issue by shahabaejaz** [codedak/chatbot#5]
python3 execute.py 

>> Mode : train

Preparing data in working_dir/
2017-09-05 16:51:11.408480: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 16:51:11.408500: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 16:51:11.408504: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 16:51:11.408508: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Creating 3 layers of 128 units.
Traceback (most recent call last):
  File "execute.py", line 290, in <module>
    train()
  File "execute.py", line 114, in train
    model = create_model(sess, False)
  File "execute.py", line 82, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "/Users/ttmac2/Documents/Shahab/MachineLearning/chatbot_model/chatbot-master/seq2seq_model.py", line 113, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/Users/ttmac2/Documents/Shahab/MachineLearning/anaconda/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1221, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "/Users/ttmac2/Documents/Shahab/MachineLearning/anaconda/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1134, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/Users/ttmac2/Documents/Shahab/MachineLearning/anaconda/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1089, in sequence_loss_by_example
    crossent = softmax_loss_function(labels=target, logits=logit)

**Comment by vkkan** [comment]
To fix that error I have used given below code on seq2seq_model.py

      def sampled_loss(labels, logits):
        labels = tf.reshape(labels, [-1, 1])
        return tf.nn.sampled_softmax_loss(tf.transpose(w), b, labels, logits, 
                                          num_samples,self.target_vocab_size)
      softmax_loss_function = sampled_loss
      setattr(tf.contrib.rnn.GRUCell, '__deepcopy__', lambda self, _: self)
      setattr(tf.contrib.rnn.BasicLSTMCell, '__deepcopy__', lambda self, _: self)
      setattr(tf.contrib.rnn.MultiRNNCell, '__deepcopy__', lambda self, _: self)
